---

- debug:
    var: ansible_os_family
    verbosity: 2

- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- include_tasks: windows.yml
  when: ansible_connection == "winrm"
