---
- name: Use package manager to remove SaltStack.
  ansible.builtin.package:
    name: "{{ saltstack_packages }}"
    state: absent
  tags:
    - packages

- name: Remove SaltStack GPG keys.
  ansible.builtin.rpm_key:
    key: "{{ item }}"
    state: absent
  loop: "{{ saltstack_keys }}"
  tags:
    - key
