---

- name: Use package manager to remove SaltStack.
  package:
    name: "{{ item }}"
    state: absent
  become: yes
  loop: "{{ saltstack_packages }}"

- name: Remove SaltStack GPG keys.
  rpm_key:
    key: "{{ item }}"
    state: absent
  become: yes
  loop: "{{ saltstack_keys }}"

- name: Remove SaltStack installed by pip.
  pip:
    name: salt
    state: absent

- name: Ensure specific paths are absent.
  file:
    path: "{{ item }}"
    state: absent
  become: yes
  loop: "{{ saltstack_paths }}"

