---

- name: Check for uninstaller executable.
  win_stat:
    path: "{{ windows_uninstaller }}"
  register: uninstall_stat

- name: Run Windows uninstaller exe.
  win_command: "{{ windows_uninstaller }} /S"
  when: uninstall_stat.stat.exists
